// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE


function make(east, north, $staropt$star, param) {
  var direction = $staropt$star !== undefined ? $staropt$star : /* NORTH */0;
  return /* record */[
          /* east */east,
          /* north */north,
          /* direction */direction
        ];
}

function moveEast(engine) {
  engine[/* east */0] = engine[/* east */0] + 1 | 0;
  return engine;
}

function moveWest(engine) {
  engine[/* east */0] = engine[/* east */0] - 1 | 0;
  return engine;
}

function moveNorth(engine) {
  engine[/* north */1] = engine[/* north */1] + 1 | 0;
  return engine;
}

function moveSouth(engine) {
  engine[/* north */1] = engine[/* north */1] - 1 | 0;
  return engine;
}

function move(engine) {
  var match = engine[/* direction */2];
  switch (match) {
    case 0 : 
        return moveNorth(engine);
    case 1 : 
        return moveSouth(engine);
    case 2 : 
        return moveEast(engine);
    case 3 : 
        return moveWest(engine);
    
  }
}

var Robot = /* module */[
  /* make */make,
  /* moveEast */moveEast,
  /* moveWest */moveWest,
  /* moveNorth */moveNorth,
  /* moveSouth */moveSouth,
  /* move */move
];

export {
  Robot ,
  
}
/* No side effect */
