// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link from "next/link";

var styles = {
  marginRight: "10px"
};

function Header(Props) {
  return React.createElement("div", undefined, React.createElement(Link.default, {
                  href: "/",
                  children: React.createElement("a", {
                        style: styles
                      }, "Home")
                }), React.createElement(Link.default, {
                  href: "/about",
                  children: React.createElement("a", {
                        style: styles
                      }, "About")
                }));
}

var make = Header;

var $$default = Header;

export {
  styles ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
