// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link from "next/link";
import * as HeaderCss from "./Header.css";

var css = HeaderCss;

function Header(Props) {
  return React.createElement("div", undefined, React.createElement(Link.default, {
                  href: "/",
                  children: React.createElement("a", {
                        className: css.withMargin
                      }, "Home")
                }), React.createElement(Link.default, {
                  href: "/about",
                  children: React.createElement("a", {
                        className: css.withMargin
                      }, "About")
                }));
}

var make = Header;

var $$default = Header;

export {
  css ,
  make ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
