// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as Router from "next/router";

function ActiveLink(Props) {
  var href = Props.href;
  var activeClassName = Props.activeClassName;
  var children = Props.children;
  var router = Router.useRouter();
  var handleClick = function ($$event) {
    $$event.preventDefault();
    router.push(href);
    return /* () */0;
  };
  var className = Cn.make(/* :: */[
        Cn.ifTrue(activeClassName, router.pathname === href),
        /* [] */0
      ]);
  return React.createElement("a", {
              className: className,
              href: href,
              onClick: handleClick
            }, children);
}

var make = ActiveLink;

var $$default = ActiveLink;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
