// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as CommandsAreaCss from "./CommandsArea.css";

var css = CommandsAreaCss;

function CommandsArea(Props) {
  var className = Props.className;
  var match = Props.defaultText;
  var defaultText = match !== undefined ? match : "";
  var match$1 = Props.textUseState;
  var match$2 = match$1 !== undefined ? match$1 : React.useState((function () {
            return defaultText;
          }));
  var match$3 = Props.text;
  var text = match$3 !== undefined ? match$3 : match$2[0];
  var match$4 = Props.setText;
  var setText = match$4 !== undefined ? match$4 : match$2[1];
  var className$1 = Cn.make(/* :: */[
        css.textArea,
        /* :: */[
          Cn.unpack(className),
          /* [] */0
        ]
      ]);
  var onTextChange = function (e) {
    return Curry._1(setText, e.target.value);
  };
  return React.createElement("textarea", {
              "aria-label": "Enter commands",
              className: className$1,
              placeholder: "Enter commands...",
              value: text,
              onChange: onTextChange
            });
}

var make = CommandsArea;

var $$default = CommandsArea;

export {
  css ,
  make ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
