// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as CommandsAreaCss from "./CommandsArea.css";

var css = CommandsAreaCss;

function CommandsArea(Props) {
  var match = Props.defaultText;
  var defaultText = match !== undefined ? match : "";
  var match$1 = Props.textUseState;
  var match$2 = match$1 !== undefined ? match$1 : React.useState((function () {
            return defaultText;
          }));
  var match$3 = Props.text;
  var text = match$3 !== undefined ? match$3 : match$2[0];
  var match$4 = Props.setText;
  var setText = match$4 !== undefined ? match$4 : match$2[1];
  var match$5 = Props.result;
  var result = match$5 !== undefined ? match$5 : "";
  var onTextChange = function (e) {
    return Curry._1(setText, e.target.value);
  };
  var onClearClick = function (param) {
    return Curry._1(setText, (function (param) {
                  return "";
                }));
  };
  return React.createElement("div", {
              className: css.container
            }, React.createElement("textarea", {
                  "aria-label": "Enter commands",
                  className: css.textArea,
                  placeholder: "Enter commands...",
                  value: text,
                  onChange: onTextChange
                }), React.createElement("div", undefined, result, React.createElement("button", {
                      className: css.button,
                      title: "Clear Text",
                      disabled: text.length === 0,
                      onClick: onClearClick
                    }, "Clear Text")));
}

var make = CommandsArea;

var $$default = CommandsArea;

export {
  css ,
  make ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
