/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const CommandsAreaBS = require('./CommandsArea.bs');

export const $$default: React.FC<{
  readonly className?: string; 
  readonly defaultText?: string; 
  readonly setText?: (_1:((_1:string) => string)) => void; 
  readonly text?: string; 
  readonly textUseState?: [string, (_1:((_1:string) => string)) => void]
}> = CommandsAreaBS.default;

export default $$default;
