// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Counter(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* count */state[/* count */0] + 1 | 0];
        }), /* record */[/* count */0]);
  var dispatch = match[1];
  var countMsg = "Count: " + String(match[0][/* count */0]);
  return React.createElement("div", undefined, React.createElement("p", undefined, countMsg), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Add */0);
                    })
                }, "Add"));
}

var make = Counter;

var $$default = Counter;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
