/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const HeaderBS = require('./Header.bs');

export const $$default: (_1:{ readonly className?: string }) => JSX.Element = HeaderBS.default;

export default $$default;
