// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as ActiveLink from "./ActiveLink.bs.js";
import * as HeaderCss from "./Header.css";

var css = HeaderCss;

function Header(Props) {
  var className = Props.className;
  var className$1 = Cn.make(/* :: */[
        css.header,
        /* :: */[
          Cn.unpack(className),
          /* [] */0
        ]
      ]);
  return React.createElement("header", {
              className: className$1
            }, React.createElement("h1", undefined, "🤖 Challenge"), React.createElement("nav", undefined, React.createElement(ActiveLink.make, {
                      href: "/",
                      activeClassName: css.active,
                      children: "Home"
                    })));
}

var make = Header;

var $$default = Header;

export {
  css ,
  make ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
