/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const HeaderBS = require('./Header.bs');

import {reactElement as ReasonReact_reactElement} from '../../src/shims/ReactShim.shim';

export const make: (_1:{}) => ReasonReact_reactElement = HeaderBS.make;
