/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const HeaderBS = require('./Header.bs');

export const $$default: React.FC<{ readonly className?: string }> = HeaderBS.default;

export default $$default;
