// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ActiveLink from "./ActiveLink.bs.js";
import * as HeaderCss from "./Header.css";

var css = HeaderCss;

function Header(Props) {
  return React.createElement("header", {
              className: css.header
            }, React.createElement("h1", undefined, "Robot Challenge"), React.createElement("nav", undefined, React.createElement(ActiveLink.make, {
                      href: "/",
                      activeClassName: css.active,
                      children: "Home"
                    }), React.createElement(ActiveLink.make, {
                      href: "/about",
                      activeClassName: css.active,
                      children: "About"
                    })));
}

var make = Header;

var $$default = Header;

export {
  css ,
  make ,
  $$default ,
  $$default as default,
  
}
/* css Not a pure module */
