/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const ToolbarBS = require('./Toolbar.bs');

export const $$default: (_1:{ readonly className?: string; readonly result?: string }) => JSX.Element = ToolbarBS.default;

export default $$default;
