/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const ToolbarBS = require('./Toolbar.bs');

export const $$default: React.ComponentType<{ readonly className?: string; readonly result?: string }> = ToolbarBS.default;

export default $$default;
