/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const ToolbarBS = require('./Toolbar.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Props = { readonly className?: string; readonly result?: string };

export const $$default: React.ComponentType<{ readonly className?: string; readonly result?: string }> = ToolbarBS.default;

export default $$default;
