// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header from "../components/Header.bs.js";
import * as Counter from "../components/Counter.bs.js";

function About(Props) {
  return React.createElement("div", undefined, React.createElement(Header.make, { }), React.createElement("p", undefined, "This is the about page."), React.createElement(Counter.make, { }));
}

var make = About;

var $$default = About;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
